### ISSUE TITLE
Param tags is no more there in PrestaShop 1.7

### ISSUE THREAD

**Issue by prestamodule** [PrestaShop/ps_wirepayment#10]
But it's still used on this template file: payment_return.tpl

**Comment by prestamodule** [comment]
https://github.com/PrestaShop/PrestaShop/commit/ddf92c287d2ab43b32a023ae78987894ad8064cb

**Comment by PrestaEdit** [comment]
Fixed in https://github.com/PrestaShop/ps_wirepayment/commit/2ce14df2a17b91e91bb4880c6c4076dc8e21001a by @antoin-m (don't hesitate to check and close Issues/Pull Request, somtimes, ...)
